#pragma once

#define DRIVER_VERSION		"v1.1.0"

/* The vendor ID this driver will work for */
#define USB_VENDOR_ID_DISTEC		0x1731

/* These are the product IDs the driver will (probably) work for */
#define USB_PRODUCT_ID_ARTISTAUSB_II_XGA_TOUCH	    0x000A
#define USB_PRODUCT_ID_ARTISTAUSB_II_XGA		    0x000B
#define USB_PRODUCT_ID_ARTISTAUSB_II_WXGA_TOUCH	    0x000C
#define USB_PRODUCT_ID_ARTISTAUSB_II_WXGA		    0x000D
#define USB_PRODUCT_ID_ARTISTAUSB_II_SVGA_TOUCH	    0x000E
#define USB_PRODUCT_ID_ARTISTAUSB_II_SVGA		    0x000F
#define USB_PRODUCT_ID_ARTISTAUSB_II_SXGA_TOUCH	    0x0010
#define USB_PRODUCT_ID_ARTISTAUSB_II_SXGA		    0x0011
#define USB_PRODUCT_ID_ARTISTAUSB_II_WVGA_TOUCH	    0x0012
#define USB_PRODUCT_ID_ARTISTAUSB_II_WVGA		    0x0013
#define USB_PRODUCT_ID_ARTISTAUSB_II_FULLHD_TOUCH   0x0014
#define USB_PRODUCT_ID_ARTISTAUSB_II_FULLHD		    0x0015
#define USB_PRODUCT_ID_ARTISTAUSB_II_VGA_TOUCH	    0x0018
#define USB_PRODUCT_ID_ARTISTAUSB_II_VGA		    0x0019
#define USB_PRODUCT_ID_ARTISTAUSB_II_WSVGA_TOUCH    0x001A
#define USB_PRODUCT_ID_ARTISTAUSB_II_WSVGA		    0x001B
/* dynamic handling of resolution: */
#define USB_PRODUCT_ID_ARTISTAUSB_II_TOUCH		    0x001D
#define USB_PRODUCT_ID_ARTISTAUSB_II			    0x001E
#define USB_PRODUCT_ID_ARTISTAUSB_ECO_VGA_TOUCH     0x0021
#define USB_PRODUCT_ID_ARTISTAUSB_ECO_VGA		    0x0022
#define USB_PRODUCT_ID_ARTISTAUSB_ECO_SVGA_TOUCH    0x0023
#define USB_PRODUCT_ID_ARTISTAUSB_ECO_SVGA		    0x0024
#define USB_PRODUCT_ID_ARTISTAUSB_ECO_XGA_TOUCH	    0x0025
#define USB_PRODUCT_ID_ARTISTAUSB_ECO_XGA           0x0026
#define USB_PRODUCT_ID_ARTISTAUSB_ECO_WSVGA_TOUCH   0x0027
#define USB_PRODUCT_ID_ARTISTAUSB_ECO_WSVGA		    0x0028
#define USB_PRODUCT_ID_ARTISTAUSB_ECO_WVGA_TOUCH    0x0029
#define USB_PRODUCT_ID_ARTISTAUSB_ECO_WVGA		    0x002A
/* 1440 x 900 - don't know a standard name for this resolution */
#define USB_PRODUCT_ID_ARTISTAUSB_ECO_1440_TOUCH    0x002B
#define USB_PRODUCT_ID_ARTISTAUSB_ECO_1440		    0x002C

